apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  labels:
    app: memory-demo
spec:
  containers:
  - name: memory-demo
    image: python:3.10
    command: ["python", "-c", "import time; x = []; for _ in range(1000000): x.append(' ' * 10**6); time.sleep(10)"]
    resources:
      requests:
        memory: "128Mi"
      limits:
        memory: "256Mi"

